services:
    apache:
        image: httpd:alpine
        ports:
            - 8888:80
            - 443:443
        volumes:
            - ./code:/var/www/html
            - ./webserver/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./data/logs:/var/log
    php:
        user: '1000:1000'
        build:
            context: ./webserver
            args:
                PHP_VERSION: ${PHP_VERSION:-8.1}
                ENV: ${ENV:-production}
        volumes:
            - ./code:/var/www/html
            - ./webserver/php-ini-overrides.ini:/usr/local/etc/php/conf.d/extra.ini
            - ./data/logs:/var/log
    database:
        image: mariadb:latest        
        ports:
            - 3306:3306
        environment:            
            MARIADB_ROOT_PASSWORD: schlucht 
            MARIADB_USER: root  
        volumes:
            - db:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - database
        environment:
            PMA_USER: root
            PMA_PASSWORD: schlucht
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8081:80
volumes:
    db:
networks:
    webserver: