version: '3'

services:
    apache:
        image: httpd:alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./code:/var/www/html
            - ./webserver/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./data/logs:/var/log
    php:
        user: '1000:1000'
        build:
            context: ./webserver
            args:
                PHP_VERSION: ${PHP_VERSION:-8.1}
                ENV: ${ENV:-production}
        volumes:
            - ./code:/var/www/html
            - ./webserver/php-ini-overrides.ini:/usr/local/etc/php/conf.d/extra.ini
            - ./data/logs:/var/log
    database:
        image: mariadb:${MARIADB_VERSION:-latest}
        ports:
            - ${DB_PUBLIC_PORT:-3306}:3306
        environment:
            - MARIADB_ROOT_PASSWORD=schlucht
        volumes:
            - db:/var/lib/mysql
    adm:
        image: adminer
        restart: always
        ports:
            - 8080:8080
volumes:
    db:
networks:
    webserver: